# Generated by Django 3.0.5 on 2020-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_consulta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(blank=True),
        ),
    ]
