# Generated by Django 3.0.5 on 2020-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_auto_20200508_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(),
        ),
    ]
