# Generated by Django 3.0.5 on 2020-04-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_auto_20200416_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587091773.339066'),
        ),
    ]
