# Generated by Django 3.0.5 on 2020-04-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0016_auto_20200417_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587092465.5673356'),
        ),
    ]
