# Generated by Django 3.0.5 on 2020-04-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0021_auto_20200422_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587605225.6222057'),
        ),
    ]
