# Generated by Django 3.0.5 on 2020-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0032_auto_20200502_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1588950598.9220552'),
        ),
    ]
