# Generated by Django 3.0.5 on 2020-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0046_auto_20200508_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1589040821.6265063'),
        ),
    ]
