# Generated by Django 3.0.5 on 2020-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0004_auto_20200416_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587091852.9772935'),
        ),
    ]
