# Generated by Django 3.0.5 on 2020-04-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0017_auto_20200417_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587092570.2576625'),
        ),
    ]
