# Generated by Django 3.0.5 on 2020-04-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0018_auto_20200417_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587092599.8880856'),
        ),
    ]
