# Generated by Django 3.0.5 on 2020-04-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0020_auto_20200418_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1587604570.9819899'),
        ),
    ]
