# Generated by Django 3.0.5 on 2020-04-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0027_auto_20200428_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1588111602.6832542'),
        ),
    ]
