# Generated by Django 3.0.5 on 2020-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0028_auto_20200428_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1588444280.8567963'),
        ),
    ]
