# Generated by Django 3.0.5 on 2020-05-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0030_auto_20200502_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1588472338.108757'),
        ),
    ]
