# Generated by Django 3.0.5 on 2020-05-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0031_auto_20200502_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1588472605.4496925'),
        ),
    ]
