# Generated by Django 3.0.5 on 2020-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendente', '0045_auto_20200508_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/1588953126.0582533'),
        ),
    ]
