# Generated by Django 3.0.5 on 2020-04-15 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame_Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glicose', models.CharField(max_length=15)),
                ('ldl_max', models.CharField(max_length=15)),
                ('hdl_max', models.CharField(max_length=15)),
                ('triglicerides_max', models.CharField(max_length=15)),
                ('colesterol_max', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame_Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateField()),
                ('glicose', models.CharField(max_length=15)),
                ('ldl', models.CharField(max_length=15)),
                ('hdl', models.CharField(max_length=15)),
                ('triglicerides', models.CharField(max_length=15)),
                ('colesterol', models.CharField(max_length=15)),
                ('pdf', models.FileField(blank=True, upload_to='pdf/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
