# Generated by Django 3.0.5 on 2020-04-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame_referencia',
            old_name='idade',
            new_name='idade_max',
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='idade_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
