# Generated by Django 3.0.5 on 2020-04-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_auto_20200422_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame_referencia',
            old_name='hdl_max',
            new_name='hdl_min',
        ),
    ]
