# Generated by Django 3.0.5 on 2020-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_auto_20200422_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame_referencia',
            name='colesterol_max',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='glicose',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='hdl_min',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='ldl_max',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='triglicerides_max',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_resultado',
            name='colesterol',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_resultado',
            name='glicose',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_resultado',
            name='hdl',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_resultado',
            name='ldl',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_resultado',
            name='triglicerides',
            field=models.FloatField(max_length=15),
        ),
    ]
