# Generated by Django 3.0.5 on 2020-04-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_auto_20200428_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame_referencia',
            name='colesterol_max',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='glicose',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='hdl_min',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='ldl_max',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='exame_referencia',
            name='triglicerides_max',
            field=models.IntegerField(max_length=15),
        ),
    ]
