# Generated by Django 3.0.5 on 2020-05-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0006_auto_20200502_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exame_referencia',
            old_name='glicose',
            new_name='colesterol_min',
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='glicose_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='glicose_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='hdl_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='ldl_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='triglicerides_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='vldl_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame_referencia',
            name='vldl_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
