# Generated by Django 3.0.5 on 2020-05-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0007_auto_20200502_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame_resultado',
            name='vldl',
            field=models.FloatField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
