# Generated by Django 3.0.5 on 2020-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('carteira_convenio', models.CharField(max_length=30, unique=True)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
            ],
        ),
    ]
