# Generated by Django 3.0.5 on 2020-04-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
