# Generated by Django 3.0.5 on 2020-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_remove_paciente_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='celular',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='end_num',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
