# Generated by Django 3.0.5 on 2020-05-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20200428_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='end_num',
            field=models.IntegerField(),
        ),
    ]
